site_name: Página de Eduardo

nav:
  - Principal: index.md
  - Práctica 15: iaw-practica-15.md
  - Práctica 16: iaw-practica-16.md

theme:
  name: material
  palette:
    primary: green
  language: es
  logo: images/flecha.png

